apiVersion: v1
kind: ConfigMap
metadata: 
  name: catalogue
  labels: 
    component: catalogue
    project: roboshop
    tier: app
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---
apiVersion: v1
kind: Deployment
metadata:
  namespace: roboshop
  name: catalogue
  labels:
    component: catalogue
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      labels: 
        component: catalogue
        project: roboshop
        tier: database
  template:
    metadata:
      labels:
        component: catalogue
        project: roboshop
        tier: database
    spec:
      containers:
        - name: catalogue
          image: saidoc11/catalogue
          envFrom:
            - configMapRef:
              name: catalogue

---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: catalogue
spec:
  selector:
    component: catalogue
    project: roboshop
    tier: database  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

              
