apiVersion: v1
kind: multi-container
metadata:
  name: nginx
  labels:
    name: roboshop
    purpose: demo
spec:
  containers:
  - name: nginx
    image": nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]