apiVersion: v1
kind: Pod
metadata: 
  name: annotations
  labels:
    project: roboshop
    purpose: demo
  annotations:
    describe: the difference between labels and annotations
    jenkins: "https://jenkins.com/build/job/roboshop-catalouge/3"
spec:
  container:
  - name: nginx
    image: nginx

  
