apiVersion: v1
kind: Pod
metadata:
  name: environment
  labels:
    project: roboshop
    purpose: demo
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: COURSE
        value: "KUBERENETS"