apiVersion: v1
kind: Pod
metadata:
  name: configenv
  labels:
    name: roboshop
    purpose: demo
spec: 
  containers:
    - name: nginx
      image: nginx
      envFrom:
        configMapRef:
          name: pod-config
  