apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue" 
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: roboshop
  name: cart
  labels: 
    component: catalogue
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: catalogue
      project: roboshop
      tier: app    
    template:
      metadata:
        labels: 
          component: catalogue
          project: roboshop
          tier: app
      spec:
        containers:
          - name: cart
            image: saidoc11/cart:v1
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    compnent: catalogue
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      
