apiVersion: app/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: redis
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:  
      component: redis
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database
    spec:
      containers:
        -  name: redis
           image: redis:7.0
---
apiVersion: v1
kind: Service
metadata: 
  namespace: roboshop
  name: redis
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6376         