apiVersion: v1 
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database
  template:
    metadata: 
      name: mongodb
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
        - name: mongodb
          image: saidoc11/mongodb:v1
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
    - project: TCP
      port: 27017
      targetPort: 27017





