apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop
  name: debug
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
    - name: debug
      image: saidoc11/debug
      command: [ "sleep", "1000" ]